(define (desinated frame)
  (let ((origin (origin-frame frame))
	(edge1 (edge1-frame frame))
	(edge2 (edge2-frame frame))
	(edge3 (add-vect edge1 edge2)))
    (list (make-segment origin edge1)
	  (make-segment edge1 edge3)
	  (make-segment edge3 edge2)
	  (make-segment edge2 origin))))
(define (X-frame frame)
  (let ((origin (origin-frame frame))
	(edge1 (edge1-frame frame))
	(edge2 (edge2-frame frame))
	(edge3 (add-vect edge1 edge2)))
    (list (make-segment origin edge3)
	  (make-segment edge1 edge2))))
