(define (insert new-num sorted-sent)
  (if (empty? sorted-sent)
      (se new-num)
      (if (<= new-num (first sorted-sent))
	  (se new-num sorted-sent)
	  (se (first sorted-sent)
	      (insert new-num (bf sorted-sent))))))
(define (insertion-sort-2 unsorted-sent)
  (if (empty? unsorted-sent)
      '()
      (insert (first unsorted-sent) (insertion-sort-2 (bf unsorted-sent)))))